name: Ping Render Backend

on:
  schedule:
    - cron: '*/14 2-16 * * *' # Every 14 mins, 2 AM to 4 PM UTC (approx)
  workflow_dispatch: # manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Render backend
        run: curl -s -o /dev/null -w "%{http_code}" https://statify-backend-vxf6.onrender.com/status
