name: pre-commit

on:
  pull_request:
    branches: [main]

jobs:
  quality-checks:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt || true
          pip install pre-commit pytest

      - name: Run pre-commit (don't fail build)
        run: pre-commit run --all-files || echo "Pre-commit checks failed, but continuing."

  run-tests:
    name: Run FastAPI tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests (don't fail build)
        run: |
          pytest -v --tb=short || echo "Tests failed, but continuing."
